### ISSUE TITLE
Last Question of Task-9 

### ISSUE THREAD

**Issue by aravindpatel** [pravinkundan/Innomatics_Internship_APR_21#1]

**Comment by aravindpatel** [comment]
> 
> 
> Last Question of Task-9 is You have to perform left tailed test but you chose right tailed test.
> check you have bold claim H1: **mu** <100
> so left tail
> @pravinkundan

**Comment by pravinkundan** [comment]
Now, I have performed left t-test.
I have to delete the previous file from lms or upload the both file.
